//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;&gt;
        ///  &lt;xsl:output  method=&quot;html&quot; omit-xml-declaration=&quot;yes&quot; indent=&quot;yes&quot;/&gt;
        ///  &lt;xsl:template match=&quot;@* | node()&quot;&gt;
        ///    &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///      &lt;tr&gt;
        ///        &lt;xsl:for-each select=&quot;/*/node()&quot;&gt;
        ///          &lt;xsl:if test=&quot;position()=1&quot;&gt;
        ///            &lt;xsl:for-each select=&quot;*&quot;&gt;
        ///              &lt;th&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DataTableHtmlXslt {
            get {
                return ResourceManager.GetString("DataTableHtmlXslt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td {
        ///    border: solid black 1px;
        ///    padding-left:5px;
        ///    padding-right:5px;
        ///    padding-top:1px;
        ///    padding-bottom:1px;
        ///    font-size:11pt;
        ///    font-family:calibri;
        ///}
        ///th {
        ///    border: solid black 1px;
        ///    padding-left:5px;
        ///    padding-right:5px;
        ///    padding-top:1px;
        ///    padding-bottom:1px;
        ///    font-size:11pt;
        ///    font-family:calibri;
        ///    font-weight:bold;
        ///    color:white;
        ///    background-color:#0080FF;
        ///}
        ///
        ///.
        /// </summary>
        public static string HtmlTableStyle {
            get {
                return ResourceManager.GetString("HtmlTableStyle", resourceCulture);
            }
        }
    }
}
